/* Generated by Yosys 0.57+153 (git sha1 6b3a7e244, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "fulladder.v:1.1-17.10" *)
module fulladder(a, b, cin, sum, carry);
  (* src = "fulladder.v:1.24-1.25" *)
  input a;
  wire a;
  (* src = "fulladder.v:1.26-1.27" *)
  input b;
  wire b;
  (* src = "fulladder.v:1.28-1.31" *)
  input cin;
  wire cin;
  (* src = "fulladder.v:1.39-1.42" *)
  output sum;
  wire sum;
  (* src = "fulladder.v:1.43-1.48" *)
  output carry;
  wire carry;
  (* src = "fulladder.v:3.9-3.11" *)
  wire _00_;
  (* src = "fulladder.v:3.12-3.14" *)
  wire _01_;
  (* src = "fulladder.v:1.43-1.48" *)
  wire _02_;
  (* src = "halfadder.v:1.24-1.25" *)
  wire _03_;
  (* src = "halfadder.v:1.26-1.27" *)
  wire _04_;
  (* src = "halfadder.v:1.39-1.44" *)
  wire _05_;
  (* src = "halfadder.v:1.35-1.38" *)
  wire _06_;
  (* src = "halfadder.v:1.24-1.25" *)
  wire _07_;
  (* src = "halfadder.v:1.26-1.27" *)
  wire _08_;
  (* src = "halfadder.v:1.39-1.44" *)
  wire _09_;
  (* src = "halfadder.v:1.35-1.38" *)
  wire _10_;
  (* src = "fulladder.v:3.9-3.11" *)
  wire c1;
  (* src = "fulladder.v:3.12-3.14" *)
  wire c2;
  (* src = "fulladder.v:3.6-3.8" *)
  wire s1;
  (* hdlname = "submod1 a" *)
  (* src = "halfadder.v:1.24-1.25" *)
  wire \submod1.a ;
  (* hdlname = "submod1 b" *)
  (* src = "halfadder.v:1.26-1.27" *)
  wire \submod1.b ;
  (* hdlname = "submod1 carry" *)
  (* src = "halfadder.v:1.39-1.44" *)
  wire \submod1.carry ;
  (* hdlname = "submod1 sum" *)
  (* src = "halfadder.v:1.35-1.38" *)
  wire \submod1.sum ;
  (* hdlname = "submod2 a" *)
  (* src = "halfadder.v:1.24-1.25" *)
  wire \submod2.a ;
  (* hdlname = "submod2 b" *)
  (* src = "halfadder.v:1.26-1.27" *)
  wire \submod2.b ;
  (* hdlname = "submod2 carry" *)
  (* src = "halfadder.v:1.39-1.44" *)
  wire \submod2.carry ;
  (* hdlname = "submod2 sum" *)
  (* src = "halfadder.v:1.35-1.38" *)
  wire \submod2.sum ;
  sky130_fd_sc_hd__or2_0 _11_ (
    .A(_01_),
    .B(_00_),
    .X(_02_)
  );
  sky130_fd_sc_hd__and2_0 _12_ (
    .A(_04_),
    .B(_03_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xor2_1 _13_ (
    .A(_04_),
    .B(_03_),
    .X(_06_)
  );
  sky130_fd_sc_hd__and2_0 _14_ (
    .A(_08_),
    .B(_07_),
    .X(_09_)
  );
  sky130_fd_sc_hd__xor2_1 _15_ (
    .A(_08_),
    .B(_07_),
    .X(_10_)
  );
  assign _01_ = c2;
  assign _00_ = c1;
  assign carry = _02_;
  assign _08_ = \submod2.b ;
  assign _07_ = \submod2.a ;
  assign \submod2.sum  = _10_;
  assign \submod2.carry  = _09_;
  assign \submod2.a  = s1;
  assign \submod2.b  = cin;
  assign c2 = \submod2.carry ;
  assign sum = \submod2.sum ;
  assign _04_ = \submod1.b ;
  assign _03_ = \submod1.a ;
  assign \submod1.sum  = _06_;
  assign \submod1.carry  = _05_;
  assign \submod1.a  = a;
  assign \submod1.b  = b;
  assign c1 = \submod1.carry ;
  assign s1 = \submod1.sum ;
endmodule
