/* Generated by Yosys 0.57+153 (git sha1 6b3a7e244, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module blocking_caveat(a, b, c, d);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output d;
  wire d;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  sky130_fd_sc_hd__o21a_1 _5_ (
    .A1(_2_),
    .A2(_1_),
    .B1(_3_),
    .X(_4_)
  );
  assign _2_ = b;
  assign _1_ = a;
  assign _3_ = c;
  assign d = _4_;
endmodule
