/* Generated by Yosys 0.57+153 (git sha1 6b3a7e244, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module mux(I0, I1, Sel, Out);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input Sel;
  wire Sel;
  output Out;
  wire Out;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_3_),
    .X(_2_)
  );
  assign _0_ = I0;
  assign _1_ = I1;
  assign _3_ = Sel;
  assign Out = _2_;
endmodule
